version: '2.1'
services:
  elasticsearch_node0:
    build:
      context: .
      dockerfile: Dockerfile_node0
    image: elasticsearch:node0
    container_name: esnode0
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 3g
    cap_add:
      - IPC_LOCK
    volumes:
      - /opt/elasticsearch/node0/data:/opt/elasticsearch/data
      - /opt/elasticsearch/node0/logs:/opt/elasticsearch/logs
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - esnet

  elasticsearch_node1:
    build:
      context: .
      dockerfile: Dockerfile_node1
    image: elasticsearch:node1
    container_name: esnode1
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 3g
    cap_add:
      - IPC_LOCK
    volumes:
      - /opt/elasticsearch/node1/logs:/opt/elasticsearch/logs
      - /opt/elasticsearch/node1/data:/opt/elasticsearch/data
    ports:
          - 9201:9200
          - 9301:9300
    networks:
      - esnet

  elasticsearch_node2:
    build:
      context: .
      dockerfile: Dockerfile_node2
    image: elasticsearch:node2
    container_name: esnode2
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 3g
    cap_add:
      - IPC_LOCK
    volumes:
      - /opt/elasticsearch/node2/logs:/opt/elasticsearch/logs
      - /opt/elasticsearch/node2/data:/opt/elasticsearch/data
    ports:
          - 9202:9200
          - 9302:9300
    networks:
      - esnet

networks:
  esnet:
    driver: bridge