FROM docker.elastic.co/elasticsearch/elasticsearch:5.2.2
ADD node2/elasticsearch.yml /usr/share/elasticsearch/config/

ENV ES_JAVA_OPTS="-Xms1536m -Xmx1536m"

USER root

RUN chown elasticsearch:elasticsearch config/elasticsearch.yml \
&& mkdir -p /opt/elasticsearch/data/escluster \
&& mkdir -p /opt/elasticsearch/logs/escluster \
&& chown -R elasticsearch:elasticsearch /opt/elasticsearch

USER elasticsearch