version: '2'
services:
  elasticsearch5:
    image: library/elasticsearch:5-alpine
    container_name: elasticsearch5
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1g
    cap_add:
      - IPC_LOCK
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elasticnet
volumes:
  esdata:
    driver: local

networks:
  elasticnet:
    driver: bridge