version: '2.1'
services:
  portainer:
      image: portainer/portainer:latest
      container_name: portainer
      ports:
        - "9010:9000"
      volumes:
        - "/var/run/docker.sock:/var/run/docker.sock"