version: '2.1'

services:
  kafka:
    image: spotify/kafka
    container_name: kafka
    hostname: kafka
    ports:
      - "2181:2181"
      - "9092:9092"
    environment:
      JMX_PORT: 9999

  kafka-manager:
    image: mmaia/kafka-manager-docker:latest
    container_name: kafka-manager
    environment:
      ZK_HOSTS: kafka:2181
    ports:
      - "9000:9000"
    depends_on:
      - kafka